gitlab:

image: index.alauda.cn/alauda/gitlab:7.9.4

links:

- redis:redis

- postgresql:postgresql

ports:

- "80"

- "22"

environment:

- DB_HOST: $POSTGRESQL_PORT_5432_TCP_ADDR

- DB_PORT: $POSTGRESQL_PORT_5432_TCP_PORT

- REDIS_HOST: $REDIS_PORT_6379_TCP_ADDR

- REDIS_PORT: $REDIS_PORT_6379_TCP_PORT

- DB_NAME=gitlabhq_production

- DB_PASS=test

- DB_TYPE=postgres

- DB_USER=gitlab

- GITLAB_SSH_PORT=22

volumes:

- /home/git/data

size: L

postgresql:

image: index.alauda.cn/alauda/postgres:9.3

expose:

- "5432"

volumes:

- /var/lib/postgresql/data

environment:

- POSTGRES_USER=gitlab

- POSTGRES_PASSWORD=test

- POSTGRES_DB=gitlabhq_production

redis:

image: index.alauda.cn/alauda/redis:2.8

expose:

- "6379"
